version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    ports:
      - "8000:8000"
  postgres:
    container_name: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: webdbuser
      POSTGRES_DB: webdb
    ports:
      - "5432:5432"